const keyMap = new Map<(number | null)[], {}>()

keyMap.set([13], {code: 'Tab', key: '\t'})
keyMap.set([13], {code: 'Enter', key: '\n'})
keyMap.set([27], {code: 'Escape', key: 'Escape'})

keyMap.set([27, 79, 80], {code: 'F1', key: 'F1'})
keyMap.set([27, 79, 81], {code: 'F2', key: 'F2'})
keyMap.set([27, 79, 82], {code: 'F3', key: 'F3'})
keyMap.set([27, 79, 83], {code: 'F4', key: 'F4'})
keyMap.set([27, 91, 49, 53, 126], {code: 'F5', key: 'F5'})
keyMap.set([27, 91, 49, 55, 126], {code: 'F6', key: 'F6'})
keyMap.set([27, 91, 49, 56, 126], {code: 'F7', key: 'F7'})
keyMap.set([27, 91, 49, 57, 126], {code: 'F8', key: 'F8'})
keyMap.set([27, 91, 50, 48, 126], {code: 'F9', key: 'F9'})
keyMap.set([27, 91, 50, 49, 126], {code: 'F10', key: 'F10'})
keyMap.set([27, 91, 50, 51, 126], {code: 'F11', key: 'F11'})
keyMap.set([27, 91, 50, 52, 126], {code: 'F12', key: 'F12'})

keyMap.set([27, 91, 50, 126], {code: 'Paste', key: 'Paste'})
keyMap.set([27, 91, 53, 126], {code: 'PageUp', key: 'PageUp'})
keyMap.set([27, 91, 54, 126], {code: 'PageDown', key: 'PageDown'})
keyMap.set([27, 91, 70], {code: 'End', key: 'End'})
keyMap.set([27, 91, 72], {code: 'Home', key: 'Home'})

keyMap.set([32], {code: 'Space', key: ' '})
keyMap.set([32], {code: 'Semicolon', key: '"'})
keyMap.set([45], {code: 'Minus', key: 'Minus'})

keyMap.set([48], {code: 'Digit0', key: '0'})
keyMap.set([49], {code: 'Digit1', key: '1'})
keyMap.set([50], {code: 'Digit2', key: '2'})
keyMap.set([51], {code: 'Digit3', key: '3'})
keyMap.set([52], {code: 'Digit4', key: '4'})
keyMap.set([53], {code: 'Digit5', key: '5'})
keyMap.set([54], {code: 'Digit6', key: '6'})
keyMap.set([55], {code: 'Digit7', key: '7'})
keyMap.set([56], {code: 'Digit8', key: '8'})
keyMap.set([57], {code: 'Digit9', key: '9'})

keyMap.set([61], {code: 'Equal', key: 'Equal'})

keyMap.set([65], {code: 'KeyA', key: 'A'})
keyMap.set([66], {code: 'KeyB', key: 'B'})
keyMap.set([67], {code: 'KeyC', key: 'C'})
keyMap.set([68], {code: 'KeyD', key: 'D'})
keyMap.set([69], {code: 'KeyE', key: 'E'})
keyMap.set([70], {code: 'KeyF', key: 'F'})
keyMap.set([71], {code: 'KeyG', key: 'G'})
keyMap.set([72], {code: 'KeyH', key: 'H'})
keyMap.set([73], {code: 'KeyI', key: 'I'})
keyMap.set([74], {code: 'KeyJ', key: 'J'})
keyMap.set([75], {code: 'KeyK', key: 'K'})
keyMap.set([76], {code: 'KeyL', key: 'L'})
keyMap.set([77], {code: 'KeyM', key: 'M'})
keyMap.set([78], {code: 'KeyN', key: 'N'})
keyMap.set([79], {code: 'KeyO', key: 'O'})
keyMap.set([80], {code: 'KeyP', key: 'P'})
keyMap.set([81], {code: 'KeyQ', key: 'Q'})
keyMap.set([82], {code: 'KeyR', key: 'R'})
keyMap.set([83], {code: 'KeyS', key: 'S'})
keyMap.set([84], {code: 'KeyT', key: 'T'})
keyMap.set([85], {code: 'KeyU', key: 'U'})
keyMap.set([86], {code: 'KeyV', key: 'V'})
keyMap.set([87], {code: 'KeyW', key: 'W'})
keyMap.set([88], {code: 'KeyX', key: 'X'})
keyMap.set([89], {code: 'KeyY', key: 'Y'})
keyMap.set([90], {code: 'KeyZ', key: 'Z'})

keyMap.set([91], {code: 'BracketLeft', key: '['})
keyMap.set([93], {code: 'BracketRight', key: ']'})

keyMap.set([97], {code: 'KeyA', key: 'a'})
keyMap.set([98], {code: 'KeyB', key: 'b'})
keyMap.set([99], {code: 'KeyC', key: 'c'})
keyMap.set([100], {code: 'KeyD', key: 'd'})
keyMap.set([101], {code: 'KeyE', key: 'e'})
keyMap.set([102], {code: 'KeyF', key: 'f'})
keyMap.set([103], {code: 'KeyG', key: 'g'})
keyMap.set([104], {code: 'KeyH', key: 'h'})
keyMap.set([105], {code: 'KeyI', key: 'i'})
keyMap.set([106], {code: 'KeyJ', key: 'j'})
keyMap.set([107], {code: 'KeyK', key: 'k'})
keyMap.set([108], {code: 'KeyL', key: 'l'})
keyMap.set([109], {code: 'KeyM', key: 'm'})
keyMap.set([110], {code: 'KeyN', key: 'n'})
keyMap.set([111], {code: 'KeyO', key: 'o'})
keyMap.set([112], {code: 'KeyP', key: 'p'})
keyMap.set([113], {code: 'KeyQ', key: 'q'})
keyMap.set([114], {code: 'KeyR', key: 'r'})
keyMap.set([115], {code: 'KeyS', key: 's'})
keyMap.set([116], {code: 'KeyT', key: 't'})
keyMap.set([117], {code: 'KeyU', key: 'u'})
keyMap.set([118], {code: 'KeyV', key: 'v'})
keyMap.set([119], {code: 'KeyW', key: 'w'})
keyMap.set([120], {code: 'KeyX', key: 'x'})
keyMap.set([121], {code: 'KeyY', key: 'y'})
keyMap.set([122], {code: 'KeyZ', key: 'z'})

keyMap.set([127], {code: 'Backspace', key: 'Backspace'})

export default keyMap;
