// deno-lint-ignore-file prefer-ascii
const keyMap = new Map<(number | null)[], {}>()

keyMap.set([0], {code: 'Null', key: '\x00'})
keyMap.set([1], {code: 'StartOfHeading', key: '\x01'})
keyMap.set([2], {code: 'StartOfText', key: '\x02'})
keyMap.set([3], {code: 'EndOfText', key: '\x03'})
keyMap.set([4], {code: 'EndOfTransmission', key: '\x04'})
keyMap.set([5], {code: 'Enquiry', key: '\x05'})
keyMap.set([6], {code: 'Acknowledge', key: '\x06'})
keyMap.set([7], {code: 'Bell', key: '\x07'})
keyMap.set([8], {code: 'Backspace', key: '\x08'})
keyMap.set([9], {code: 'HorizontalTab', key: '\t'})
keyMap.set([10], {code: 'LineFeed', key: '\n'})
keyMap.set([11], {code: 'VerticalTab', key: '\x0b'})
keyMap.set([12], {code: 'FormFeed', key: '\x0c'})
keyMap.set([13], {code: 'Enter', key: '\n'})
keyMap.set([14], {code: 'ShiftOut', key: '\x0e'})
keyMap.set([15], {code: 'ShiftIn', key: '\x0f'})
keyMap.set([16], {code: 'DataLinkEscape', key: '\x10'})
keyMap.set([17], {code: 'DeviceControlOne', key: '\x11'})
keyMap.set([18], {code: 'DeviceControlTwo', key: '\x12'})
keyMap.set([19], {code: 'DeviceControlThree', key: '\x13'})
keyMap.set([20], {code: 'DeviceControlFour', key: '\x14'})
keyMap.set([21], {code: 'NegativeAcknowledge', key: '\x15'})
keyMap.set([22], {code: 'SynchronousIdle', key: '\x16'})
keyMap.set([23], {code: 'EndOfTransmissionBlock', key: '\x17'})
keyMap.set([24], {code: 'Cancel', key: '\x18'})
keyMap.set([25], {code: 'EndOfMedium', key: '\x19'})
keyMap.set([26], {code: 'Substitute', key: '\x1a'})
keyMap.set([27], {code: 'Escape', key: '\x1b'})

keyMap.set([27, 79, 80], {code: 'F1', key: 'F1'})
keyMap.set([27, 79, 81], {code: 'F2', key: 'F2'})
keyMap.set([27, 79, 82], {code: 'F3', key: 'F3'})
keyMap.set([27, 79, 83], {code: 'F4', key: 'F4'})
keyMap.set([27, 91, 49, 53, 126], {code: 'F5', key: 'F5'})
keyMap.set([27, 91, 49, 55, 126], {code: 'F6', key: 'F6'})
keyMap.set([27, 91, 49, 56, 126], {code: 'F7', key: 'F7'})
keyMap.set([27, 91, 49, 57, 126], {code: 'F8', key: 'F8'})

keyMap.set([27, 91, 49, 59, 53, 65], {code: 'ArrowUp', key: 'ArrowUp'})
keyMap.set([27, 91, 49, 59, 53, 66], {code: 'ArrowDown', key: 'ArrowDown'})
keyMap.set([27, 91, 49, 59, 53, 67], {code: 'ArrowRight', key: 'ArrowRight'})
keyMap.set([27, 91, 49, 59, 53, 68], {code: 'ArrowLeft', key: 'ArrowLeft'})

keyMap.set([27, 91, 50, 48, 126], {code: 'F9', key: 'F9'})
keyMap.set([27, 91, 50, 49, 126], {code: 'F10', key: 'F10'})
keyMap.set([27, 91, 50, 51, 126], {code: 'F11', key: 'F11'})
keyMap.set([27, 91, 50, 52, 126], {code: 'F12', key: 'F12'})

keyMap.set([27, 91, 50, 126], {code: 'Paste', key: 'Paste'})
keyMap.set([27, 91, 51, 126], {code: 'Delete', key: 'Delete'})
keyMap.set([27, 91, 53, 126], {code: 'PageUp', key: 'PageUp'})
keyMap.set([27, 91, 54, 126], {code: 'PageDown', key: 'PageDown'})


keyMap.set([27, 91, 65], {code: 'ArrowUp', key: 'ArrowUp'})
keyMap.set([27, 91, 66], {code: 'ArrowDown', key: 'ArrowDown'})
keyMap.set([27, 91, 67], {code: 'ArrowRight', key: 'ArrowRight'})
keyMap.set([27, 91, 68], {code: 'ArrowLeft', key: 'ArrowLeft'})

keyMap.set([27, 91, 70], {code: 'End', key: 'End'})
keyMap.set([27, 91, 72], {code: 'Home', key: 'Home'})

keyMap.set([28], {code: 'FileSeparator', key: '\x1c'})
keyMap.set([29], {code: 'GroupSeparator', key: '\x1d'})
keyMap.set([30], {code: 'RecordSeparator', key: '\x1e'})
keyMap.set([31], {code: 'UnitSeparator', key: '\x1f'})

keyMap.set([32], {code: 'Space', key: ' '})
keyMap.set([33], {code: 'ExclamationMark', key: '!'})
keyMap.set([34], {code: 'DoubleQuotation', key: '"'})
keyMap.set([35], {code: 'Hash', key: '#'})
keyMap.set([36], {code: 'Dollar', key: '$'})
keyMap.set([37], {code: 'Percent', key: '%'})
keyMap.set([38], {code: 'And', key: '&'})
keyMap.set([39], {code: 'SingleQuotation', key: '\''})
keyMap.set([40], {code: 'ParenthesesLeft', key: '('})
keyMap.set([41], {code: 'ParenthesesRight', key: ')'})
keyMap.set([42], {code: 'Multiply', key: '*'})
keyMap.set([43], {code: 'Add', key: '+'})
keyMap.set([45], {code: 'Minus', key: '-'})
keyMap.set([46], {code: 'Period', key: '.'})
keyMap.set([47], {code: 'Slash', key: '/'})

keyMap.set([48], {code: 'Digit0', key: '0'})
keyMap.set([49], {code: 'Digit1', key: '1'})
keyMap.set([50], {code: 'Digit2', key: '2'})
keyMap.set([51], {code: 'Digit3', key: '3'})
keyMap.set([52], {code: 'Digit4', key: '4'})
keyMap.set([53], {code: 'Digit5', key: '5'})
keyMap.set([54], {code: 'Digit6', key: '6'})
keyMap.set([55], {code: 'Digit7', key: '7'})
keyMap.set([56], {code: 'Digit8', key: '8'})
keyMap.set([57], {code: 'Digit9', key: '9'})

keyMap.set([58], {code: 'Colon', key: ':'})
keyMap.set([59], {code: 'Semicolon', key: ';'})
keyMap.set([60], {code: 'Backquote', key: '<'})
keyMap.set([61], {code: 'Equal', key: '='})
keyMap.set([62], {code: 'Backquote', key: '>'})
keyMap.set([63], {code: 'QuestionMark', key: '?'})
keyMap.set([64], {code: 'AtSign', key: '@'})

keyMap.set([65], {code: 'KeyA', key: 'A'})
keyMap.set([66], {code: 'KeyB', key: 'B'})
keyMap.set([67], {code: 'KeyC', key: 'C'})
keyMap.set([68], {code: 'KeyD', key: 'D'})
keyMap.set([69], {code: 'KeyE', key: 'E'})
keyMap.set([70], {code: 'KeyF', key: 'F'})
keyMap.set([71], {code: 'KeyG', key: 'G'})
keyMap.set([72], {code: 'KeyH', key: 'H'})
keyMap.set([73], {code: 'KeyI', key: 'I'})
keyMap.set([74], {code: 'KeyJ', key: 'J'})
keyMap.set([75], {code: 'KeyK', key: 'K'})
keyMap.set([76], {code: 'KeyL', key: 'L'})
keyMap.set([77], {code: 'KeyM', key: 'M'})
keyMap.set([78], {code: 'KeyN', key: 'N'})
keyMap.set([79], {code: 'KeyO', key: 'O'})
keyMap.set([80], {code: 'KeyP', key: 'P'})
keyMap.set([81], {code: 'KeyQ', key: 'Q'})
keyMap.set([82], {code: 'KeyR', key: 'R'})
keyMap.set([83], {code: 'KeyS', key: 'S'})
keyMap.set([84], {code: 'KeyT', key: 'T'})
keyMap.set([85], {code: 'KeyU', key: 'U'})
keyMap.set([86], {code: 'KeyV', key: 'V'})
keyMap.set([87], {code: 'KeyW', key: 'W'})
keyMap.set([88], {code: 'KeyX', key: 'X'})
keyMap.set([89], {code: 'KeyY', key: 'Y'})
keyMap.set([90], {code: 'KeyZ', key: 'Z'})

keyMap.set([91], {code: 'BracketLeft', key: '['})
keyMap.set([92], {code: 'Backslash', key: '\\'})
keyMap.set([93], {code: 'BracketRight', key: ']'})
keyMap.set([94], {code: 'Caret', key: '^'})
keyMap.set([95], {code: 'Underscore', key: '_'})
keyMap.set([96], {code: 'Backquote', key: '`'})

keyMap.set([97], {code: 'KeyA', key: 'a'})
keyMap.set([98], {code: 'KeyB', key: 'b'})
keyMap.set([99], {code: 'KeyC', key: 'c'})
keyMap.set([100], {code: 'KeyD', key: 'd'})
keyMap.set([101], {code: 'KeyE', key: 'e'})
keyMap.set([102], {code: 'KeyF', key: 'f'})
keyMap.set([103], {code: 'KeyG', key: 'g'})
keyMap.set([104], {code: 'KeyH', key: 'h'})
keyMap.set([105], {code: 'KeyI', key: 'i'})
keyMap.set([106], {code: 'KeyJ', key: 'j'})
keyMap.set([107], {code: 'KeyK', key: 'k'})
keyMap.set([108], {code: 'KeyL', key: 'l'})
keyMap.set([109], {code: 'KeyM', key: 'm'})
keyMap.set([110], {code: 'KeyN', key: 'n'})
keyMap.set([111], {code: 'KeyO', key: 'o'})
keyMap.set([112], {code: 'KeyP', key: 'p'})
keyMap.set([113], {code: 'KeyQ', key: 'q'})
keyMap.set([114], {code: 'KeyR', key: 'r'})
keyMap.set([115], {code: 'KeyS', key: 's'})
keyMap.set([116], {code: 'KeyT', key: 't'})
keyMap.set([117], {code: 'KeyU', key: 'u'})
keyMap.set([118], {code: 'KeyV', key: 'v'})
keyMap.set([119], {code: 'KeyW', key: 'w'})
keyMap.set([120], {code: 'KeyX', key: 'x'})
keyMap.set([121], {code: 'KeyY', key: 'y'})
keyMap.set([122], {code: 'KeyZ', key: 'z'})

keyMap.set([123], {code: 'BracesLeft', key: '{'})
keyMap.set([124], {code: 'Pipe', key: '|'})
keyMap.set([125], {code: 'BracesRight', key: '}'})

keyMap.set([126], {code: 'Tilde', key: '~'})
keyMap.set([127], {code: 'Backspace', key: 'Backspace'})

keyMap.set([128], {code: 'EuroSign', key:'€'})
keyMap.set([130], {code: 'SingleLow9QuotationMark', key:'‚'})
keyMap.set([131], {code: 'LatinSmallLetterFWithHook', key:'ƒ'})
keyMap.set([132], {code: 'DoubleLow9QuotationMark', key:'„'})
keyMap.set([133], {code: 'HorizontalEllipsis', key:'…'})
keyMap.set([134], {code: 'Dagger', key:'†'})
keyMap.set([135], {code: 'DoubleDagger', key:'‡'})
keyMap.set([136], {code: 'ModifierLetterCircumflexAccent', key:'ˆ'})
keyMap.set([137], {code: 'PerMilleSign', key:'‰'})
keyMap.set([138], {code: 'LatinCapitalLetterSWithCaron', key:'Š'})
keyMap.set([139], {code: 'SingleLeftPointingAngleQuotation', key:'‹'})
keyMap.set([140], {code: 'LatinCapitalLigatureOE', key:'Œ'})
keyMap.set([141], {code: 'Unused', key: undefined})
keyMap.set([142], {code: 'LatinCapitalLetterZWithCaron', key:'Ž'})
keyMap.set([143], {code: 'Unused', key: undefined})
keyMap.set([144], {code: 'Unused', key: undefined})
keyMap.set([145], {code: 'LeftSingleQuotationMark', key:'‘'})
keyMap.set([146], {code: 'RightSingleQuotationMark', key:'’'})
keyMap.set([147], {code: 'LeftDoubleQuotationMark', key:'“'})
keyMap.set([148], {code: 'RightDoubleQuotationMark', key:'”'})
keyMap.set([149], {code: 'Bullet', key:'•'})
keyMap.set([150], {code: 'EnDash', key:'–'})
keyMap.set([151], {code: 'EmDash', key:'—'})
keyMap.set([152], {code: 'SmallTilde', key:'˜'})
keyMap.set([153], {code: 'TradeMarkSign', key:'™'})
keyMap.set([154], {code: 'LatinSmallLetterSWithCaron', key:'š'})
keyMap.set([155], {code: 'SingleRightPointingAngleQuotationMark', key: '›'})
keyMap.set([156], {code: 'LatinSmallLigatureOe', key:'œ'})
keyMap.set([157], {code: 'Unused', key: undefined})
keyMap.set([158], {code: 'LatinSmallLetterZWithCaron', key:'ž'})
keyMap.set([159], {code: 'LatinCapitalLetterYWithDiaeresis', key:'Ÿ'})
keyMap.set([160], {code: 'NonBreakingSpace', key:'NBSP'})
keyMap.set([161], {code: 'InvertedExclamationMark', key:'¡'})
keyMap.set([162], {code: 'CentSign', key:'¢'})
keyMap.set([163], {code: 'PoundSign', key:'£'})
keyMap.set([164], {code: 'CurrencySign', key:'¤'})
keyMap.set([165], {code: 'YenSign', key:'¥'})
keyMap.set([166], {code: 'BrokenVerticalBar', key:'¦'})
keyMap.set([167], {code: 'Paragraph', key:'§'})
keyMap.set([168], {code: 'SpacingDiaeresisUmlaut', key:'¨'})
keyMap.set([169], {code: 'CopyrightSign', key:'©'})
keyMap.set([170], {code: 'FeminineOrdinalIndicator', key:'ª'})
keyMap.set([171], {code: 'LeftDoubleAngleQuotes', key:'«'})
keyMap.set([172], {code: 'Negation', key:'¬'})
keyMap.set([173], {code: 'SoftHyphen', key:'­SHY'})
keyMap.set([174], {code: 'RegisteredTradeMarkSign', key:'®'})
keyMap.set([175], {code: 'SpacingMacronOverline', key:'¯'})
keyMap.set([176], {code: 'DegreeSign', key:'°'})
keyMap.set([177], {code: 'PlusOrMinusSign', key:'±'})
keyMap.set([178], {code: 'SuperscriptTwoSquared', key:'²'})
keyMap.set([179], {code: 'SuperscriptThreeCubed', key:'³'})
keyMap.set([180], {code: 'AcuteAccentSpacingAcute', key:'´'})
keyMap.set([181], {code: 'MicroSign', key:'µ'})
keyMap.set([182], {code: 'PilcrowSignParagraphSign', key:'¶'})
keyMap.set([183], {code: 'MiddleDotGeorgianComma', key:'·'})
keyMap.set([184], {code: 'SpacingCedilla', key:'¸'})
keyMap.set([185], {code: 'SuperscriptOne', key:'¹'})
keyMap.set([186], {code: 'MasculineOrdinalIndicator', key:'º'})
keyMap.set([187], {code: 'RightDoubleAngleQuotes', key:'»'})
keyMap.set([188], {code: 'FractionOneQuarter', key:'¼'})
keyMap.set([189], {code: 'FractionOneHalf', key:'½'})
keyMap.set([190], {code: 'FractionThreeQuarters', key:'¾'})
keyMap.set([191], {code: 'InvertedQuestionMark', key:'¿'})
keyMap.set([192], {code: 'LatinCapitalLetterAWithGrave', key:'À'})
keyMap.set([193], {code: 'LatinCapitalLetterAWithAcute', key:'Á'})
keyMap.set([194], {code: 'LatinCapitalLetterAWithCircumflex', key:'Â'})
keyMap.set([195], {code: 'LatinCapitalLetterAWithTilde', key:'Ã'})
keyMap.set([196], {code: 'LatinCapitalLetterAWithDiaeresis', key:'Ä'})
keyMap.set([197], {code: 'LatinCapitalLetterAWithRingAbove', key:'Å'})
keyMap.set([198], {code: 'LatinCapitalLetterAE', key:'Æ'})
keyMap.set([199], {code: 'LatinCapitalLetterCWithCedilla', key:'Ç'})
keyMap.set([200], {code: 'LatinCapitalLetterEWithGrave', key:'È'})
keyMap.set([201], {code: 'LatinCapitalLetterEWithAcute', key:'É'})
keyMap.set([202], {code: 'LatinCapitalLetterEWithCircumflex', key:'Ê'})
keyMap.set([203], {code: 'LatinCapitalLetterEWithDiaeresis', key:'Ë'})
keyMap.set([204], {code: 'LatinCapitalLetterIWithGrave', key:'Ì'})
keyMap.set([205], {code: 'LatinCapitalLetterIWithAcute', key:'Í'})
keyMap.set([206], {code: 'LatinCapitalLetterIWithCircumflex', key:'Î'})
keyMap.set([207], {code: 'LatinCapitalLetterIWithDiaeresis', key:'Ï'})
keyMap.set([208], {code: 'LatinCapitalLetterETH', key:'Ð'})
keyMap.set([209], {code: 'LatinCapitalLetterNWithTilde', key:'Ñ'})
keyMap.set([210], {code: 'LatinCapitalLetterOWithGrave', key:'Ò'})
keyMap.set([211], {code: 'LatinCapitalLetterOWithAcute', key:'Ó'})
keyMap.set([212], {code: 'LatinCapitalLetterOWithCircumflex', key:'Ô'})
keyMap.set([213], {code: 'LatinCapitalLetterOWithTilde', key:'Õ'})
keyMap.set([214], {code: 'LatinCapitalLetterOWithDiaeresis', key:'Ö'})
keyMap.set([215], {code: 'MultiplicationSign', key:'×'})
keyMap.set([216], {code: 'LatinCapitalLetterOWithSlash', key:'Ø'})
keyMap.set([217], {code: 'LatinCapitalLetterUWithGrave', key:'Ù'})
keyMap.set([218], {code: 'LatinCapitalLetterUWithAcute', key:'Ú'})
keyMap.set([219], {code: 'LatinCapitalLetterUWithCircumflex', key:'Û'})
keyMap.set([220], {code: 'LatinCapitalLetterUWithDiaeresis', key:'Ü'})
keyMap.set([221], {code: 'LatinCapitalLetterYWithAcute', key:'Ý'})
keyMap.set([222], {code: 'LatinCapitalLetterTHORN', key:'Þ'})
keyMap.set([223], {code: 'LatinSmallLetterSharpSEssZed', key:'ß'})
keyMap.set([224], {code: 'LatinSmallLetterAWithGrave', key:'à'})
keyMap.set([225], {code: 'LatinSmallLetterAWithAcute', key:'á'})
keyMap.set([226], {code: 'LatinSmallLetterAWithCircumflex', key:'â'})
keyMap.set([227], {code: 'LatinSmallLetterAWithTilde', key:'ã'})
keyMap.set([228], {code: 'LatinSmallLetterAWithDiaeresis', key:'ä'})
keyMap.set([229], {code: 'LatinSmallLetterAWithRingAbove', key:'å'})
keyMap.set([230], {code: 'LatinSmallLetterAe', key:'æ'})
keyMap.set([231], {code: 'LatinSmallLetterCWithCedilla', key:'ç'})
keyMap.set([232], {code: 'LatinSmallLetterEWithGrave', key:'è'})
keyMap.set([233], {code: 'LatinSmallLetterEWithAcute', key:'é'})
keyMap.set([234], {code: 'LatinSmallLetterEWithCircumflex', key:'ê'})
keyMap.set([235], {code: 'LatinSmallLetterEWithDiaeresis', key:'ë'})
keyMap.set([236], {code: 'LatinSmallLetterIWithGrave', key:'ì'})
keyMap.set([237], {code: 'LatinSmallLetterIWithAcute', key:'í'})
keyMap.set([238], {code: 'LatinSmallLetterIWithCircumflex', key:'î'})
keyMap.set([239], {code: 'LatinSmallLetterIWithDiaeresis', key:'ï'})
keyMap.set([240], {code: 'LatinSmallLetterEth', key:'ð'})
keyMap.set([241], {code: 'LatinSmallLetterNWithTilde', key:'ñ'})
keyMap.set([242], {code: 'LatinSmallLetterOWithGrave', key:'ò'})
keyMap.set([243], {code: 'LatinSmallLetterOWithAcute', key:'ó'})
keyMap.set([244], {code: 'LatinSmallLetterOWithCircumflex', key:'ô'})
keyMap.set([245], {code: 'LatinSmallLetterOWithTilde', key:'õ'})
keyMap.set([246], {code: 'LatinSmallLetterOWithDiaeresis', key:'ö'})
keyMap.set([247], {code: 'DivisionSign', key:'÷'})
keyMap.set([248], {code: 'LatinSmallLetterOWithSlash', key:'ø'})
keyMap.set([249], {code: 'LatinSmallLetterUWithGrave', key:'ù'})
keyMap.set([250], {code: 'LatinSmallLetterUWithAcute', key:'ú'})
keyMap.set([251], {code: 'LatinSmallLetterUWithCircumflex', key:'û'})
keyMap.set([252], {code: 'LatinSmallLetterUWithDiaeresis', key:'ü'})
keyMap.set([253], {code: 'LatinSmallLetterYWithAcute', key:'ý'})
keyMap.set([254], {code: 'LatinSmallLetterThorn', key:'þ'})
keyMap.set([255], {code: 'LatinSmallLetterYWithDiaeresis', key:'ÿ'})

export default keyMap;
